updated text-recognization file
AOSP-NIT-Surat/Bookstore-ML pull request #9
Opened 2021-10-04 12:11 UTC by vivektangudu2024

used isbn number of book to print Author name and publisher 
from the text recognized by natik

2021-10-06 13:15 UTC, GrayFlash commented
Hey nice!! Btw move your file to a directory named `PyScripts`, and will be great if you could add a demo on the data that can be obtained.

2021-10-06 16:15 UTC, vivektangudu2024 commented
i tested on this

2021-10-06 16:15 UTC, vivektangudu2024 commented
![test](https://user-images.githubusercontent.com/75472985/136243026-57c8176b-65d6-4eae-9c8f-21c653b54804.jpg)

2021-10-06 16:16 UTC, vivektangudu2024 commented
![py](https://user-images.githubusercontent.com/75472985/136243159-425f675d-2335-4809-acd6-b4f4cb91183a.PNG)

2021-10-06 16:16 UTC, vivektangudu2024 commented
this is the output

2021-10-06 19:14 UTC, GrayFlash requested changes

2021-10-06 19:14 UTC, GrayFlash commented on Pyscripts/Text_recognization.py
> +#pip install isbntools
can you update the requirements.txt file with these pip packages?? Also remove these from the final file.

2021-10-06 19:14 UTC, GrayFlash commented on Pyscripts/Text_recognization.py
> +
no need of this extra line between two imports

2021-10-06 19:14 UTC, GrayFlash commented on Pyscripts/Text_recognization.py
> +reader = easyocr.Reader(['en'])
we can create a function here?? it should accept `imagePath` here, and then we can perform the ISBN reading from image??

2021-10-06 19:14 UTC, GrayFlash commented on Pyscripts/Text_recognization.py
> +    #print(text)
remove commented logging statements

2021-10-06 19:14 UTC, GrayFlash commented on Pyscripts/Text_recognization.py
> +print(registry.bibformatters['labels'](meta(get_isbn)))
remove multiple blank lines and use a return statement here, possibly return a dictionary.

2021-10-06 19:14 UTC, GrayFlash commented on Pyscripts/Text_recognization.py
> +print(registry.bibformatters['labels'](meta(get_isbn)))
also leave a blank line at the end of files.

2021-10-07 04:01 UTC, vivektangudu2024 commented
![py2](https://user-images.githubusercontent.com/75472985/136318259-96d97079-3372-4783-a95b-e5984819cf86.PNG)

2021-10-07 04:02 UTC, vivektangudu2024 commented
these are the keys respectively

2021-10-08 02:11 UTC, GrayFlash approved these changes
LGTM!!

2021-10-08 02:12 UTC, merged